config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get 'download_sample', to: 'home#download_sample'

  resources :student_records do
    collection do
      post :import
      delete 'destroy_all', to: 'student_records#destroy_all'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student_record.rb
# frozen_string_literal: true

require 'csv'

class StudentRecord < ApplicationRecord
  belongs_to :user

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, :surname, :grade, :status, presence: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { scope: :user_id }
  validates :test1, :test2, :test3, :test4, :final, numericality:  { in: 0..100 } 

  def self.import(file, user)
    result = { success: false, validation_errors: [] }
    required_columns = new.required_columns
    csv = new.csv_file(file)
    unexpected_columns = csv.headers - required_columns
    missing_columns = required_columns - csv.headers

    if unexpected_columns.any?
      result[:validation_errors] << "Unexpected columns in row: #{unexpected_columns.join(', ')}"
    elsif missing_columns.any?
      result[:validation_errors] << "Missing columns in row: #{missing_columns.join(', ')}"
    else
      csv.each_with_index do |row, i|
        student_record = new(row.to_hash)
        student_record.user = user

        unless student_record.save
          result[:validation_errors].concat(["Row #{i + 1}: #{student_record.errors.full_messages.join(', ')}, delete the records and import again"])
          break
        end
      end

      result[:success] = result[:validation_errors].empty?
    end

    result
  end  

  def total_scores_sum
    test1 + test2 + test3 + test4 + final
  end

  def total_scores_avg
    total_scores_sum / 5
  end

  def highest_score
    student_scores.max
  end

  def lowest_score
    student_scores.min
  end

  def performance_check
    case total_scores_avg
    when 90..100
      'High'
    when 70..90
      'Medium'
    else
      'Low'
    end
  end

  def csv_file(file)
    file = File.open(file)
    csv = CSV.parse(file, headers: true)
    csv
  end

  def required_columns
    %w[name surname email test1 test2 test3 test4 final grade status]
  end

  def self.ransackable_attributes(_auth_object = nil)
    [
      "grade",
      "status",
      "name",
      "surname",
      "final"
    ]
  end

  private

  def student_scores
    [test1, test2, test3, test4, final]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :student_records, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def download_sample
    file_path = Rails.root.join('public', 'student_records.csv')

    send_file(file_path, filename: 'student_records.csv', type: 'text/csv')
  end
end

app/controllers/student_records_controller.rb
# frozen_string_literal: true

class StudentRecordsController < ApplicationController
  before_action :authenticate_user!

  def index
    @q = current_user.student_records.ransack(params[:q])
    @pagy, @student_records = pagy(@q.result)
  end

  def import
    file = params[:file]
    if !file || file.content_type != 'text/csv'
      return redirect_to student_records_path, notice: "Please upload CSV files"
    end

    import_result = StudentRecord.import(file, current_user)

    if import_result[:success]
      redirect_to student_records_path, notice: 'Student records were successfully imported!'
    else
      flash[:error] = "CSV import failed: #{import_result[:validation_errors].join('; ')}"
      redirect_to student_records_path
    end
  end

  def destroy_all
    current_user.student_records.destroy_all

    redirect_to student_records_path, notice: 'All records have been successfully deleted.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/student_records_helper.rb
module StudentRecordsHelper
  def grade_options_to_select
    %w[A B C D E F]
  end

  def status_options_to_select
    %w[Pass Fail]
  end

  def sort_options_to_select
    %w[name surname final]
  end
end

app/views/home/index.html.erb
<div class="w-3/5 mx-auto">
  <h1 class="text-4xl font-bold text-indigo-700 m-3">Welcome!</h1>

  <div class="bg-white p-4 shadow-md rounded-md">
      <h2 class="text-xl font-semibold text-indigo-700 mb-2">Happy to see you on our webpage</h2>
      <p class="text-gray-600">Our user-friendly platform allows you to upload student records via
      csv file and observe academic results of your students through the automatic operations we 
      make after your upload. You are also allowed to filter and sort through your records to make 
      your experience even more efficient.</p>
      <p class="text-gray-600 mb-3">Kindly, check our sample file to see what kind of records input we expect from you!</p>
      

      <h2 class="text-lg text-gray-600 my-3">To learn more</h3>
      <%= link_to 'Download Sample File', download_sample_path, class: "bg-indigo-700 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" %>
      <div class="flex items-center space-x-4 my-3">
        <% if user_signed_in? %>
          <%= link_to 'I want to import', student_records_path, class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out' %>
          <%= button_to 'logout', destroy_user_session_path, method: :delete, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out' %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out' %>
          <span class="text-gray-400">|</span>
          <%= link_to 'Log in', new_user_session_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out' %>
        <% end%>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvUploads</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <div class="container mx-auto p-4">
    <div class="w-3/5 mx-auto">
      <% if notice %>
        <p class="my-4 px-4 py-2 text-green-700"><%= notice %></p>
      <% end %>
      <% if flash[:error] %>
        
        <p class="my-4 px-4 py-2 text-red-700"><%= flash[:error] %></p>
      <% end %>
    </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/student_records/_search_form.html.erb
<div class='flex items-center justify-between bg-white space-x-4 max-w-md p-6 rounded-md shadow-md mt-5'>
  <%= search_form_for q do |f| %>
    <div class="flex-1 mr-4">
      <%= f.label :status_eq, 'Status:', class: 'block text-gray-600 text-sm font-medium mt-2' %>
      <%= f.select :status_eq, options_for_select(status_options_to_select),  include_blank: 'Please select', class: 'w-full p-2 border rounded-md' %>
    </div>
    <div class="flex-1 mr-4">
      <%= f.label :grade_eq, 'Grade:', class: 'block text-gray-600 text-sm font-medium mt-2' %>
      <%= f.select :grade_eq, options_for_select(grade_options_to_select), include_blank: 'Please select', class: 'w-full p-2 border rounded-md' %>
      </div>
      <div class="flex-1 mr-4 mb-4">
        <%= f.label :s, 'Sort by:', class: 'block text-gray-600 text-sm font-medium mt-2' %>
        <%= f.select :s, options_for_select(sort_options_to_select.map { |opt| [opt.humanize, opt] }), include_blank: 'Please select', class: 'w-full p-2 border rounded-md' %>
      </div>
      <%= f.submit 'Search', class: 'bg-indigo-700 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded' %>
  <% end %>
  <%= link_to 'Clear all filters', student_records_path, class: "bg-gray-300 hover:bg-gray-500 text-gray-600 font-bold py-2 px-4 rounded" %>
</div>

app/views/student_records/_table_of_records.html.erb
<table class="w-full border-collapse border-t-2 border-l-2 border-b-2 border-gray-800 p-2 mt-5">
  <thead>
    <tr>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Name</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Surname</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Email</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Test1</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Test2</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Test3</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Test4</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Final</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Grade</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Status</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Total scores sum</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Total scores avg</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Highest score</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Lowest score</th>
      <th class="border-b-2 border-r-2 border-gray-700 p-2">Performance</th>
    </tr>
  </thead>
    <% student_records.each do |student_record| %>
      <tbody>
        <tr>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.name %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.surname %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.email %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.test1 %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.test2 %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.test3 %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.test4 %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.final %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.grade %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.status %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.total_scores_sum %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.total_scores_avg %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.highest_score %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.lowest_score %></td>
          <td class="border-b-2 border-r-2 border-gray-700 p-2"><%= student_record.performance_check %></td>
        </tr>
      </tbody>
    <% end %>
</table>

<div class="mt-4">
  <nav class="flex justify-between">
    <span class="py-2 px-4 bg-gray-200 rounded-md">
      <%== pagy_nav(pagy) %>
    </span>
  </nav>
</div>

app/views/student_records/index.html.erb
<div class = "w-4/5 mx-auto">
  <div class="flex items-center justify-between mb-5">
    <%= link_to '<--Back', root_path, class: "text-2xl text-blue-500 hover:underline" %>
      <% if user_signed_in? %>
        <%= button_to 'logout', destroy_user_session_path, method: :delete, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out'  %>
     <% end %>

  </div>
  <div class="bg-white p-6 rounded-md shadow-md flex items-center justify-between space-x-4">
    <%= form_with(url: import_student_records_path, method: :post, class: "p-6") do |f| %>
      <%= f.file_field :file, accept: '.csv', class: "w-full p-2 border rounded-mdblock text-gray-600 text-sm font-medium mb-2" %>
      <%= f.submit 'Import', class: "bg-indigo-700 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" %>
    <% end %>
    <%= button_to 'Destroy all records', destroy_all_student_records_path, method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
  </div>

  <% if @student_records.any? %>
    <%= turbo_frame_tag 'records_search' do %>
      <%= render 'search_form', q: @q %>
      <%= render 'table_of_records', student_records: @student_records, pagy: @pagy %>
    <% end %>
    <div class="loading-ring fixed-center-block hidden"><div>
  <% end %>
</div>